# Generated by Django 4.2.11 on 2024-06-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('place', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('abstract_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField()),
                ('type_a', models.CharField(choices=[('PLAKAT', 'PLAKAT'), ('REFERAT', 'REFERAT'), ('REFERAT LUB PLAKAT', 'REFERAT LUB PLAKAT')], max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=500)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='konferencje.conference')),
            ],
        ),
    ]
