# Generated by Django 4.2.11 on 2024-05-19 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='animals')),
            ],
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('REF_allele', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('T', 'T'), ('G', 'G')], max_length=1)),
                ('ALT_allele', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('T', 'T'), ('G', 'G')], max_length=1)),
                ('MAF', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp.chromosome')),
            ],
        ),
        migrations.AddField(
            model_name='chromosome',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp.species'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp.snp')),
            ],
        ),
    ]
